solutions/trimatoi.go, tests/pointone_test/main.go, tests/trimatoi_test/main.go
`trimatoi_test` :
- the solution was incorrect, some times it passed and sometimes it did not
- added extra cases to test (for the test cases that did not pass)
`pointone_test`:
- function `PointOne` was not being used
=> fix: inconsistencies and errors

solutions/printmemory.go, tests/printmemory_test/main.go
Refactoring the solution and the tests to a simpler and cleaner version. Fixing also a space before each of the `\n` in the soltuion.
In order to test this exercise, the correct solution is in the PR https://github.com/01-edu/piscine-go/pull/3
=> Fix printmemory - Go exam exercise

solutions/hiddenp/main.go, tests/foreach_test/main.go, tests/range_test/main.go, tests/reverserange_test/main.go
- `hiddenp`: optimization of the solutions
- `foreach_test`: little change
- `range_test` and `reverserange_test`: better consistency between tests
=> exam03 review and test

tests/rot14_test/main.go, tests/wdmatch_test/main.go
improved test for:
1) rot14 (added some extra singular cases)
2) wdmatch (added the example of the readme as a first test)
=> Tests improvement1

tests/piglatin_test/main.go
It was testing with lots of arguments, when it should be one at a time.
=> piglatin Tests fix

solutions/options/main.go, tests/findprevprime_test/main.go, tests/options_test/main.go
`options/main.go` : optimization
`findprevprime_test/main.go`: adding extra test case
=> optimization: final exam

tests/doop_test/main.go, tests/gcd_test/main.go
doop and gcd tests improvements. 
1) Less random tests to improve speed of testing. 
2) Adding of examples in the readme for gcd.
=> Tests improvement2

solutions/romannumbers/main.go
grammar correction in exercise. Corrected in public pr #795 as well.
=> correction of grammar in the test of romannumbers

lib/challenge/challenge.go, solutions/maxwordcountn.go, tests/maxwordcountn_test/main.go
Tested and written with @Frenchris
=> New exercice proposal to use maps in the piscine

solutions/printevenarguments/main.go, tests/printevenarguments_test/main.go
Add tests and solution for printevenarguments subject.
=> 1273 printevenarguments 1

solutions/descendcomb.go, tests/descendcomb_test/main.go
Created and added  test/solution for new go exercise descendcomb
=> DEV-3494-feat(piscine-go): add test/solution for new go exercise descendcomb

solutions/podiumposition.go, tests/podiumposition_test/main.go
Created and added the solution & test for new go exercise podiumposition.
=> DEV-3502-new go exercise podiumposition

solutions/reversemenuindex.go, tests/reversemenuindex_test/main.go
Created and added the solution and test for the new go exercise reversemenuindex
=> DEV-3514-new go exercise reversemenuindex

solutions/shoppingsummarycounter.go, tests/shoppingsummarycounter_test/main.go
Created and added the solution/test for the new go exercise shoppingsummarycounter.
=> DEV-3516-new go exercise shoppingsummarycounter

solutions/fooddeliverytime.go, tests/fooddeliverytime_test/main.go
Created and added the solution and test for the new go exercise fooddeliverytime.
=> DEV-3518-feat(piscine-go): add solution/test for new go exercise fooddeliverytime

solutions/dealapackofcards.go, tests/dealapackofcards_test/main.go
Created and added solution and test for the new go exercise dealapackofcards
=> DEV-3519-feat(piscine-go): add solution/test for new go exercise dealapackofcards

solutions/rockandroll.go, tests/rockandroll_test/main.go
Created and added test/solution.
=> DEV-3505-new go exercise rocknroll

test_all.sh, test_one.sh
Added missing script to test the exercises in the macbook.
=> fix(test_all-test_one): fix script for macbook

solutions/multorsum.go, tests/multorsum_test/main.go
Add test and solution for multorsum subject
=> DEV-3886-1270 multorsum 1

solutions/rectperimeter.go, tests/rectperimeter_test/main.go
=> DEV-3884-Add Solution & Test: Rect Perimeter exam function

solutions/issamestring.go, tests/issamestring_test/main.go
=> DEV-3883-feat(issamestring): solution and testing program

solutions/byebyefirst.go, tests/byebyefirst_test/main.go
Implement solution and tests for byebyefirst subject.
=> DEV-3882-1276 byebyefirst test

solutions/only1/main.go, tests/only1_test/main.go
Created PR and fixed indentation
=> DEV-3387 new go exercise only 1

lib/challenge/challenge.go, tests/quad_test/main.go
This possible improvement was reported in this [PR from jesjos]( https://github.com/01-edu/go-tests/pull/20)
- Improve the readability on how the errors (mainly I/O) are handled or discarded by explicitly take the results of I/O functions.
- Better names for some variables used by tests.
Thanks a lot to jesjos for the contribution.
=> DEV-4209 improvements-go-test

tests/listremoveif_test/main.go
adding missing tests to remove head node
=> DEV 4751: listremoveif adding missing tests

solutions/bezero.go, tests/bezero_test/main.go
Created this branch with the test/solution for the new go exercise bezero in order to solve the conflicts of the previous branch.
=> DEV-3202-feat(bezero): add solution/test for new go exercise bezero

solutions/quarterofayear.go, tests/quarterofayear_test/main.go
Added test/solution for new go exam exercise quarterofayear.
=> DEV-3378-new-go-exercise-quarterofayearfeat(go-exam): add test/solution for new go exam exercise quarterofayear

solutions/halfslice.go, tests/halfslice_test/main.go
Added test and solution for Go exam halfslice
=> DEV-3188-feat(halfslice): add test/solution for Go exam halfslice

solutions/secondhalf.go, tests/secondhalf_test/main.go
Added test and solution for the exercise secondhalf in te Go Exam.
=> DEV-3189-feat(secondhalf): add test/solution for new go exam exercise

solutions/concatslice.go, tests/concatslice_test/main.go
Created this branch in order to solve conflicts from the previous branch.
=> DEV-3183-feat(concatslice): add test/solution for exercise concatslice

solutions/hashcode.go, tests/hashcode_test/main.go
Created this branch with the test/solution for the new go exercise hashcode in order to solve the conflicts of the previous branch.
=> DEV-3200-feat(hashcode): add test/solution for new go exercise hashcode

solutions/setspace.go, tests/setspace_test/main.go
Created this branch with the test/solution for the new go exercise setspace in order to solve the conflicts of the previous branch.
=> DEV-3203-feat(setspace): add test/solution for new go exercise setspace

solutions/printif.go
=> fix(printif): fix edge case of input 0 len

tests/issorted_test/main.go
- add tests to check if the student solution is using the function passed as argument
=> CON-1852 improve issorted test

solutions/fifthandskip.go
the solution was not returning the rigth output
=> CON-2434 fifthandskip solution

tests/revconcatalternate_test/main.go
- Compare output of submitted function with expected result instead of reference function's output.
=> CON2492 update-test-of- `revconcatalternate`

solutions/canjump.go, tests/canjump_test/main.go
CON-2642 
canjump solution and test
=> CON-2642 canjump solution and test

tests/lastword_test/main.go
=> CON-3036 Fix `lastword` test

solutions/hiddenp/main.go
=> CON-3302 Fix `hiddenp` solution
